export const planCategories = [
  "Family Trip",
  "Friend Trip",
  "Couple Trip",
  "Weekend Trip",
  "Solo Trip",
  "Community Trip",
  "Group Trip",
  "Honeymoon Trip",
  "Corporate Trip",
  "International Trip",
  "Multi-National Trip",
  "Bike Trip",
  "Car Trip",
  "Backpacking Trip",
];
