export const planTypes = [
  "Departure",
  "Arrive",
  "Stay",
  "Offbeat Location",
  "Site Scene",
  "City Visit",
  "Shopping",
  "View Point",
  "Nature",
  "Park",
  "Botanical Garden",
  "Forest",
  "Waterfall",
  "Cave",
  "Tunnel",
  "Sea Beach",
  "Historical Place",
  "Fort",
  "Island",
  "Temple",
  "Church",
  "Masjid",
  "Activity",
  "Water Activity",
  "Trek",
  "Airport",
  "Railway Station",
  "Bus Stand",
  "Other",
];